name: hng_my_portfolio
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: ComfortaaLight
      fonts:
        - asset: assets/fonts/Comfortaa-Light.ttf
        
    - family: ComfortaaRegular
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
        
    - family: ComfortaaBold
      fonts:
        - asset: assets/fonts/Comfortaa-Bold.ttf